apiVersion: v1
kind: Service
metadata:
  name: nextjs-app
  namespace: prod
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nextjs-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
